let inputA;
let inputB;
let inputC;
inputA=prompt("Điểm lý");
inputB=prompt("Điểm hóa");
inputC=prompt("Điểm sinh");
let a=parseInt(inputA);
let b=parseInt(inputB);
let c=parseInt(inputC);
let TB=(a+b+c)/3;
document.write("Điểm Trung bình = "+TB);